### ISSUE TITLE
Track leadership commitment 

### ISSUE THREAD

**Issue by twentysixmoons** [open-austin/org#294]
We need a sheet that documents when people have joined leadership. This will help us keep track of how long people have agreed to commit to so we can plan to replace them if their agreed upon term is coming to an end.

**Comment by JMensch** [comment]
@VictoriaODell is this still relevant?

**Comment by VictoriaODell** [comment]
@JMensch I would think so. It would be helpful for keeping track of commitments and help with rolling people off and on. I'm sure there are terms with the board members too so that's something else we should be tracking.

**Comment by lianilychee** [comment]
closed - stale
