### ISSUE TITLE
Get Google for Non-Profits

### ISSUE THREAD

**Issue by twentysixmoons** [open-austin/org#314]
I believe @jonplaca brought this up at one point. 

Once we are our registered as own non-profit we can get the google suite for free. 

Here are the requirements:
https://www.google.com/nonprofits/eligibility/
<img width="698" alt="screen shot 2017-11-30 at 9 07 44 am" src="https://user-images.githubusercontent.com/10767430/33437599-15a86c7c-d5ae-11e7-8133-db4a574b5c9a.png">

**Comment by jonplaca** [comment]
@VictoriaODell This should be available now. Please see the Open Austin Drive > Legal > Federal Documents > "2018 05 - Open Austin - 501c3 confirmation.pdf" for proper documentation.


Removing the "Blocked" label since this is no longer the case.

**Comment by JMensch** [comment]
Keeping this around until we resolve the 501c3 debate.

**Comment by mateoclarke** [comment]
hmm, i don't know if we should've closed this...

**Comment by mateoclarke** [comment]
@JMensch, this might be something we should add to our plate of work. Especially if we decide to go basic and implement our accounting in Google Sheets as a first pass. Felt like we leaning towards a purpose built platform like Open Collective or Zipbooks last night.

Either way, knocking this out seems like the basic foundational stuff we could knock out.

**Comment by lianilychee** [comment]
closing old ticket; we've had Google for NPOs for 5 years now (summer 2019)
