### ISSUE TITLE
Project Intake v2

### ISSUE THREAD

**Issue by mscarey** [open-austin/org#334]
Not many people are starting projects through open-austin.org's [project page](https://www.open-austin.org/projects/) or [project process page](https://www.open-austin.org/projects/process). We should think about redesigning the interface for project onboarding, which currently flows from our project page to our github [project-ideas issue tracker](https://github.com/open-austin/project-ideas/issues).

I'd be curious whether people are getting to the projects page but just not finding the interface convenient enough to start on a project, or whether they're not going to the projects page at all.

**Comment by JMensch** [comment]
Looks like we have google analytics set up on our site (https://github.com/open-austin/open-austin.github.io/blob/bc2e114cc03dfc49410b4df992af4515171b8331/_includes/google-analytics.html#L7), can someone give me access to the dashboard please? @mateoclarke @VictoriaODell 

@mscarey what do you think adding project "types"? E.g. Idea, Idea w/ external stakeholder, Ongoing, etc. Idea here is to give folks a sense of project stability.

**Comment by JMensch** [comment]
Formally kicking off this project! Here's [the brief](https://docs.google.com/document/d/1ME3sTcw19Ok-WmdWLZgBK6ta5PO0Tw6bFhRfvfamE7I/edit?usp=sharing).

**Comment by JMensch** [comment]
Also dropping Oli's idea from Slack here so we don't lose it:

```
I'm wondering whether the project ideas is where most folks tend to land when they come to Open Austin. As in, do they come to Open Austin with an idea? If so, perhaps there's a way to create a one page application form outside of a new platform (away from Github) that is both open-ended and educational.

Maybe show an example or two of best-of's, and maybe one minimum amount of information required for an idea to get kicked off.
```

**Comment by mateoclarke** [comment]
Don't think this should've been closed. There were folks working on it at the last Community Action Night on 4/1.

**Comment by JMensch** [comment]
That is correct, apologies for missing this. I'm going disable stale bot in the iced-coffee repo, but I still think we need some sort of issue management for the project-ideas repo (https://github.com/open-austin/iced-coffee/issues/336). Best time to revisit that is probably after we redefine what project intake looks like in this project.

**Comment by JMensch** [comment]
This has taken a bit of a backseat for more immediate priorities (#355 and #354 chief among them) and I feel like I'm bottlenecking progress. Any interest in taking ownership here, operationally or entirely, @mscarey or @olitreadwell?

**Comment by mscarey** [comment]
@olitreadwell and I discussed adding a github widget to the projects page that would provide some kind of view of project activity or open issues, to make it easier for people to get involved from there. A cursory search didn't turn up any good widget for doing what we wanted. My very limited Ruby makes it hard for me to make structural changes to the Jekyll site.

I think I'll try pruning the project-ideas issues, which I see @VictoriaODell did a while back. I think it's a little awkward for us to take all the descriptive tags off the older ones and replace them with an "inactive" tag, but still not close the issue. It would probably be better if people could still search for older ideas based on the tags. If by "inactive" we mean we never want people to find the issue or work on it ever again, it would be better to close the issue than delete all the tags. And the "inactive" tag (similar to the "stale" tag we've been discussing lately) doesn't help users much because they could see the lack of activity anyway by checking the date of the last comment.

**Comment by mateoclarke** [comment]
I like the approach of closing out inactives instead of tagging. Also noting that Javascript is an option for pulling in data into Jekyll from 3rd party sources. Probably would need to be that anyways to pull data asynchronously from Github each time a user visits the page. If it were in Ruby, updates to the project listing would only update on site rebuild. Jekyll isn't dynamic, its static. But you could write Javascript that is dynamic on top of the static pages. Make sense?

**Comment by lianilychee** [comment]
closing - stale
