### ISSUE TITLE
Document tax filing process for 2019

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/org#346]
how do we reproduce tax filing the future?

**Comment by mscarey** [comment]
All we did for 2018 was the IRS 990-N form. If you log into Open Austin's IRS account, you'll see it. The bigger issue for 2019 will probably be providing donors with documentation of their tax-deductible contributions.

**Comment by mateoclarke** [comment]
@JMensch we should investigate how Open Collective (or any other tool we consider for donations and expenses) could help provide donors with a receipt of their tax-contributions at end of year for tax reporting requirements. I did a quick search but it might be easier to see once an account is actually created. Hoping we could at least export a list of donors and automate a batch email with the required fields. Seems like email would be fine as written acknowledgement from this [IRS page](https://www.irs.gov/charities-non-profits/charitable-organizations/charitable-contributions-written-acknowledgments)

@mscarey what is the link to Open Austin's IRS account? Are we storing credentials in a shared/secure way? I don't have access to our LastPass account right now. Just want to document how to login.

For the purposes of centralizing this information as documentation, I'm surfacing this OA folder under Finanacnes > Taxes:
https://drive.google.com/drive/folders/1Lm9UnUmlDcfCCj6To4aDUR0-t5LUOlra
I'm noticing there that the e-Postcard form is saved as HTML. Is there a better format we could save it in for better accessibility?
