### ISSUE TITLE
Finish OpenCollective page

### ISSUE THREAD

**Issue by thebestmensch** [open-austin/org#359]
Our OpenCollective site is [live](https://opencollective.com/open-austin) and can accept [donations](https://opencollective.com/open-austin/donate).

We still have a few things to do:

- [ ] Finish the site copy. Do we want to maintain things like `Updates` or `Events`? Any updates to the `About` section?
- [ ] Finalize contribution tiers. I copied ours from [Code for Denver](https://opencollective.com/codefordenver).
- [ ] Do we want to expose a budget? Seems like most OpenCollective's have one, and it's a nice visual. 
- [ ] Do we want any comms about this? Blog post or tweet?
- [ ] Add our bank account

For reference:
- [Code for Denver](https://opencollective.com/codefordenver)
- [Code for Miami](https://opencollective.com/codeformiami)
- [Women Who Code ATL](https://opencollective.com/wwcodeatl)

Would love input from @mscarey @mateoclarke @VictoriaODell

**Comment by mateoclarke** [comment]
Advice I got from CfD was avoid Events feature. I think having an open budget would be great. Maybe that's a separate issue for us to work on in iced-coffee. We should have a pretty updated list of expense data Vickie exported from Expensify to base to create a budget from.

**Comment by lianilychee** [comment]
closing - stale
