### ISSUE TITLE
Audit Leadership Needs, Roles, & Responsibilities

### ISSUE THREAD

**Issue by thebestmensch** [open-austin/org#360]
I want to take a look at our [existing](https://github.com/open-austin/iced-coffee/wiki/Team-Roles-and-Responsibilities) Leadership roles & responsibilities docs and update them given our current workload and needs.

Goals:
- Document all of the things OA Leadership is responsible for and which role is responsible.
- Have a better understanding of the world of work the Leadership team is responsible for, and who is responsible for which specific work.
- Provide a more visible & accessable way for members to understand what Leadership is responsible for and where our gaps are.
- Have a document we can give to folks interested in leadership roles.
- Have a document we can reference when advertising for leadership roles.

Resources:
- [2018 Community Action Night Playbook ](https://docs.google.com/document/d/15TOa0-pXkHlmMTGZBWTq9yf3KIQW_3ViCFfLsg7eK1U/edit)

https://brigade.codeforamerica.org/resources

**Comment by mateoclarke** [comment]
Seems like we have two new resources that capture this effort:
- https://docs.google.com/document/d/14h7hswEGK-mDCKWudgO7xHcYbkFmf-vGVRRIaAaUzYM/edit
- https://docs.google.com/document/d/1NdVlXrWK4gGvz55lxRrPfxI5ZvDUY8u142wMjuT2trg/edit#heading=h.k02b0h8hg3jb

Do we need to do more work on this besides continued discussion and recruiting folks to fill these needs @JMensch?

**Comment by JMensch** [comment]
I'm thinking two more steps and then we can move on from this:

- Combine those two docs into one source of truth for the role/responsibility combinations
- Get final :+1: from everyone on the current leadership team

**Comment by VictoriaODell** [comment]
Also throwing the Community Action Night documentation here since I think it's relevant in splitting up roles:
https://docs.google.com/document/d/15TOa0-pXkHlmMTGZBWTq9yf3KIQW_3ViCFfLsg7eK1U/edit?usp=sharing

And folder full of event volunteer descriptions for community action night: 
https://drive.google.com/open?id=0BwKb2oghmQldZEplZGVGWnZZams

**Comment by JMensch** [comment]
Stumbled across a recent doc Shellee was working on today:

https://docs.google.com/document/d/1hp8VukaqkWlsBSu5ndeksknoqhGxWG61mXdhcNmjvIM/edit?usp=sharing

Will probably be useful when we finalize this.
