### ISSUE TITLE
Messaging / Comms style guide

### ISSUE THREAD

**Issue by thebestmensch** [open-austin/org#361]
I would like to create a style guide defining (at least)
    - Messaging (everything from our website header to blog post title format)
    - Logos and their usage

I believe this would accomplish:
- Consistency across our online presences (Twitter, OpenCollective, Github, Website, etc)
- Provide a "cookbook" for anyone on Leadership that wants to communicate with the public about OA. 
- Accelerate leadership onboarding

**Comment by lianilychee** [comment]
closing - stale
