### ISSUE TITLE
OA Wiki / Docs

### ISSUE THREAD

**Issue by thebestmensch** [open-austin/org#367]
We need a single, searchable, historical, and linkable source of truth for all of our documentation.

It should, at least:

- Support search
- Have linkable topics and articles 

Initial thoughts: 
Github and google docs provide us with a change history, which may be useful down the line. Worth considering one of those solutions?

View https://github.com/open-austin/iced-coffee/issues/274 for insight into a previous try.

**Comment by lianilychee** [comment]
closing - stale
