### ISSUE TITLE
Internal Processes

### ISSUE THREAD

**Issue by thebestmensch** [open-austin/org#370]
Goal: 

Define the world of processes folks would like defined. Easy, right :trollface:? But seriously, if we plan to grow (leadership or membership), we need to have how we operate written down somewhere. Consider this issue the place to add anything you ever wish we had documented, or if you ever wanted to do something but didn't know how. I'll keep the "Master List" of requested processes up to date.

PS: what I mean by "process" is a document that anyone can follow and complete the task.

Master List

- Levels of commitment to OA and respective obligations (e.g. leadership vs general member)
- How to onboard/offboard a member to a higher level of commitment (e.g. to leadership)
- How leadership decides to commit to doing something (seems silly, but we don't really have a process for when we have opposing views on proposed work. For example, if Mateo thinks this issue is a bad idea, what do we do? Do we trust that these adhoc conversations are always going to produce the best outcome for our membership? Are we documenting *why* something was or wasn't done?)
- how to set an Open Austin project up with cloud hosting
- how to book meeting rooms through the Austin Public Library

**Comment by JMensch** [comment]
Things I think we should define:

- Levels of commitment to OA and respective obligations (e.g. leadership vs general member)
- How to onboard/offboard a member to a higher level of commitment (e.g. to leadership)
- How leadership decides to commit to doing something (seems silly, but we don't really have a process for when we have opposing views on proposed work. For example, if Mateo thinks this issue is a bad idea, what do we do? Do we trust that these adhoc conversations are always going to produce the best outcome for our membership? Are we documenting *why* something was or wasn't done?)

**Comment by mscarey** [comment]
how to set an Open Austin project up with cloud hosting

**Comment by mateoclarke** [comment]
- how to book meeting rooms through the Austin Public Library

**Comment by JMensch** [comment]
- process for member input or questions and our response.

**Comment by mscarey** [comment]
How to book a meeting room for Capital Factory (and who the best contact is).
How a sponsor can make a donation (!)

**Comment by JMensch** [comment]
This one is a big one, would love input!

I worry about biweekly checkins becoming more of a problem than a solution as the leadership team expands. I want to be as efficient as possible and process-ize the *shit* out of this, but I also don't want this to feel like work to anyone. Here's a few road bumps I've experienced when a remote team scaled (not all solvable) that might catalyze a discussion:

- How do we keep topics relevant to majority? How do we ensure someone isn't frequently in the minority? 
- How do we limit the topic list to things that benefit from in-person discussion?
- How do we limit friction when adding a next step to task management?
- How do we decide things (ideally in a timely manner)?
- How do we politely get back on topic when someone goes on a tangent?

Two big ones for me personally right now:

- How do we easily know if a time sensitive task is on track?
- How do we easily know all of OA's ongoing initiatives.

**Comment by Kristen5** [comment]
> 
> 
>     * how to book meeting rooms through the Austin Public Library
https://library.austintexas.gov/meeting-rooms/how-to-reserve

**Comment by avickers** [comment]
Should there maybe be a project champion tier between OA leadership and general member?

**Comment by lianilychee** [comment]
closing - stale
